server:
  port: 7999
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
spring:
  #邮件服务
  mail:
    host: smtp.qq.com             #邮箱服务器地址
    username: apesing@qq.com      #用户名
    password: iumgbpjzkniybjgg    #密码
    default-encoding: UTF-8       #编码
    port: 465                     #端口
    #配置SSL访问
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  datasource:
   username: sa
   password: 123456
   driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
   url: jdbc:sqlserver://39.106.15.164:59157;databasename=dbLataleAccount
   hikari:
    minimum-idle: 10
    maximum-pool-size: 25
    auto-commit: true
    idle-timeout: 300000
    pool-name: ExpendHikariCP
    max-lifetime: 1800000
    connection-timeout: 300000
    connection-test-query: select 1 from charinfo
mail:
  fromMail:
    addr: apesing@qq.com         #以谁来发送邮件
  logMail:                       #日志发送地址
    addr: 815566704@qq.com